"""
Pydantic schemas for the Assessment entity.

The ``AssessmentWithExplanations`` schema is the primary response format
for the scoring API. It includes structured feature contributions that
are safe to render directly in a reviewer dashboard.

The anomaly schemas (``AnomalyFlagSchema``, ``AnomalyReportSchema``,
``PolicyRecommendationSchema``) mirror the fraud-shield report stored in
the ``anomaly_report`` JSONB column, so a stored report round-trips into
an API response without translation.

The ``CaseBriefResponse`` schema carries the bilingual synthesis (English
executive brief + Urdu applicant explanation) generated by the case
brief service, with an award package and provenance ``mode``.
"""

import uuid
from datetime import datetime

from pydantic import BaseModel, ConfigDict

from app.utils.enums import (
    AnomalySeverity,
    ConfidenceLevel,
    PolicyActionType,
    RiskLevel,
    ScoreBand,
)


class FeatureContribution(BaseModel):
    """One feature's impact on the score, in reviewer-readable language."""

    feature: str
    label: str | None = None
    contribution: float
    direction: str # "positive", "negative", or "neutral"
    explanation: str # Plain-language sentence for the reviewer
    raw_value: float | None = None
    no_data: bool = False # True when the feature had no underlying data


# ── Anomaly / fraud shield ──────────────────────────────────────────────────


class AnomalyFlagSchema(BaseModel):
    """One fraud-shield rule firing, with its evidence."""

    code: str # e.g. "INCOME_BILL_MISMATCH"
    severity: AnomalySeverity
    title: str # Short headline for queue badges
    message: str # Reviewer-readable explanation
    evidence: dict = {} # The numeric facts behind the flag


class PolicyRecommendationSchema(BaseModel):
    """The institutional action recommended for this applicant."""

    action_type: PolicyActionType
    recommended_support: str # e.g. "Full Merit-Need Scholarship (100% Tuition)"
    summary_justification: str # Two sentences, explainable to donors


class AnomalyReportSchema(BaseModel):
    """Full fraud-shield report attached to an assessment."""

    risk_score: float = 0.0
    risk_level: RiskLevel = RiskLevel.CLEAN
    audit_required: bool = False
    flags_count: int = 0
    flags: list[AnomalyFlagSchema] = []
    top_flags: list[str] = [] # Codes of the most severe findings, worst first
    recommendation: PolicyRecommendationSchema | None = None


# ── Assessments ─────────────────────────────────────────────────────────────


class AssessmentRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    applicant_id: uuid.UUID
    score: float
    band: ScoreBand
    model_version: str
    is_rule_based: bool
    confidence_level: ConfidenceLevel
    # Data sufficiency — first-class fields, not side metadata.
    signal_categories_count: int = 0
    non_null_feature_count: int = 0
    # Anomaly shield summary — flat so the reviewer queue can show and
    # filter on it without loading the full report.
    anomaly_risk_score: float = 0.0
    anomaly_risk_level: RiskLevel = RiskLevel.CLEAN
    anomaly_audit_required: bool = False
    anomaly_flags_count: int = 0
    top_flags: list[str] = []
    created_at: datetime


class AssessmentWithExplanations(AssessmentRead):
    """Full assessment with reviewer-facing feature explanations."""

    feature_contributions: list[FeatureContribution] | None = None

    # Human-readable summary of data completeness.
    data_sufficiency_summary: str | None = None
    categories_present: list[str] | None = None
    months_of_data: int | None = None

    # Full fraud-shield report with flags, evidence, and the policy
    # recommendation (the summary fields above are flattened from it).
    anomaly_report: AnomalyReportSchema | None = None

    # Cached bilingual case brief (generated on demand, persisted for speed).
    case_brief: dict | None = None


# ── Case brief (bilingual synthesis) ─────────────────────────────────────────


class EnglishBriefSchema(BaseModel):
    """Executive briefing sections for institutional reviewers."""

    key_strengths: str
    vulnerability_profile: str
    contradiction_analysis: str
    directive: str


class AwardPackageSchema(BaseModel):
    """Concrete disbursement plan mapped from the anomaly recommendation."""

    tier: str
    conditions: list[str] = []
    disbursement_schedule: str = ""


class CaseBriefResponse(BaseModel):
    """Full bilingual synthesis of one scored applicant."""

    english_brief: EnglishBriefSchema
    urdu_brief: str
    recommended_award_package: AwardPackageSchema
    mode: str = "template" # "qwen" | "template"
