"""add training label columns to applicants

Revision ID: 0002_add_labels
Revises: 0001_initial
Create Date: 2026-01-02 00:00:00.000000

Adds reviewer_approved (boolean) and approval_score (float) columns to the
applicants table. These are synthetic ground-truth labels generated by the
seed script for model training. They are nullable because production
applicants will not have labels — only seeded synthetic ones do.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0002_add_labels"
down_revision: Union[str, None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "applicants",
        sa.Column("reviewer_approved", sa.Boolean, nullable=True),
    )
    op.add_column(
        "applicants",
        sa.Column("approval_score", sa.Float, nullable=True),
    )


def downgrade() -> None:
    op.drop_column("applicants", "approval_score")
    op.drop_column("applicants", "reviewer_approved")
